services:
  grafana:
    image: grafana/grafana-oss:10.3.3
    container_name: grafana
    ports:
      - 3000:3000
    restart: always
    env_file:
      - /opt/grafana/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/grafana/grafana-data:/var/lib/grafana
      - /opt/grafana/ldap.toml:/etc/grafana/ldap.toml
    environment:
      - TZ=Europe/Paris
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=EXPLOIT
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_ANONYMOUS_HIDE_VERSION=true
      - GF_AUTH_LDAP_ENABLED=true
      - GF_AUTH_LDAP_ALLOW_SIGN_UP=true
      - GF_AUTH_LDAP_SKIP_ORG_ROLE_SYNC=false
      - GF_AUTH_LDAP_CONFIG_FILE=/etc/grafana/ldap.toml
      - GF_SERVER_DOMAIN=metrologie-exploit.dsi.inrae.fr
      - GF_SERVER_ROOT_URL=https://metrologie-exploit.dsi.inrae.fr
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_UNIFIED_ALERTING_ENABLED=false
      - GF_ALERTING_ENABLED=false
      - GF_EXPLORE_ENABLED=false
      - GF_HELP_ENABLED=false
      - GF_METRICS_ENABLED=false
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=60s
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgres:5432
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_SSL_MODE=disable
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  postgres:
    restart: always
    container_name: postgres
    image: bitnami/postgresql:15
    environment:
      - TZ=Europe/Paris
      - POSTGRESQL_LOG_HOSTNAME=true
      - POSTGRESQL_USERNAME=grafana
      - POSTGRESQL_DATABASE=grafana
    env_file:
      - /opt/grafana/.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/grafana/postgres-data:/bitnami/postgresql
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M