apiVersion: v1
data:
  init.sql: |-
    \echo 'Running table creation script...'

    CREATE DATABASE grafana;
    CREATE TABLE supetable (id SERIAL PRIMARY KEY, name VARCHAR(50));
    INSERT INTO supetable (name) VALUES ('supe Data');
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: postgres
  name: postgres-cm0
