apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: GF_DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: GF_DATABASE_PASSWORD
                  name: postgres-env
            - name: PGPASSWORD
              valueFrom:
                configMapKeyRef:
                  key: PGPASSWORD
                  name: postgres-env
            - name: POSTGRESQL_DATABASE
              value: grafana
            - name: POSTGRESQL_LOG_HOSTNAME
              value: "true"
            - name: POSTGRESQL_USERNAME
              value: grafana
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-env
            - name: TZ
              value: Europe/Paris
          image: bitnami/postgresql:15
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              memory: "536870912"
            requests:
              memory: "268435456"
          volumeMounts:
            - mountPath: /etc/localtime
              name: postgres-cm0
              readOnly: true
              subPath: localtime
            - mountPath: /bitnami/postgresql
              name: postgres-cm1
              subPath: postgresql
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: localtime
                path: localtime
            name: postgres-cm0
          name: postgres-cm0
        - configMap:
            items:
              - key: postgres-data
                path: postgresql
            name: postgres-cm1
          name: postgres-cm1
